const booksOfBible = [
    { "title":"Genesis","value":"Genesis",},
    { "title":"Exodus", "value":"Exodus", },
    { "title":"Leviticus","value":"Leviticus",},
    { "title":"Numbers","value":"Numbers",},
    { "title":"Deuteronomy","value":"Deuteronomy",},
    { "title":"Joshua","value":"Joshua",},
    { "title":"Judges","value":"Judges",},
    { "title":"Ruth","value":"Ruth",},
    { "title":"1 Samuel","value":"1 Samuel",},
    { "title":"2 Samuel","value":"2 Samuel",},
    { "title":"1 Kings","value":"1 Kings",},
    { "title":"2 Kings","value":"2 Kings",},
    { "title":"1 Chronicles","value":"1 Chronicles",},
    { "title":"2 Chronicles","value":"2 Chronicles",},
    { "title":"Ezra","value":"Ezra",},
    { "title":"Nehemiah","value":"Nehemiah",},
    { "title":"Esther","value":"Esther",},
    { "title":"Job","value":"Job",},
    { "title":"Psalms","value":"Psalms",},
    { "title":"Proverbs","value":"Proverbs",},
    { "title":"Ecclesiastes","value":"Ecclesiastes",},
    { "title":"Song of Solomon","value":"Song of Solomon",},
    { "title":"Isaiah","value":"Isaiah",},
    { "title":"Jeremiah","value":"Jeremiah",},
    { "title":"Lamentations","value":"Lamentations",},
    { "title":"Ezekiel","value":"Ezekiel",},
    { "title":"Daniel","value":"Daniel",},
    { "title":"Hosea","value":"Hosea",},
    { "title":"Joel","value":"Joel",},
    { "title":"Amos","value":"Amos",},
    { "title":"Obadiah","value":"Obadiah",},
    { "title":"Jonah","value":"Jonah",},
    { "title":"Micah","value":"Micah",},
    { "title":"Nahum","value":"Nahum",},
    { "title":"Habakkuk","value":"Habakkuk",},
    { "title":"Zephaniah","value":"Zephaniah",},
    { "title":"Haggai","value":"Haggai",},
    { "title":"Zechariah","value":"Zechariah",},
    { "title":"Malachi","value":"Malachi",},     
    
];

export default booksOfBible;




/* 

[
    "Genesis", 
    "Exodus", 
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "1 Chronicles",
    "2 Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs",
    "Ecclesiastes",
    "Song of Solomon",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1 Corinthians",
    "2 Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "Jude",
    "Revelation"]

    Array [
        Object {
          "characters": Array [          ],
          "created": "2014-12-10T14:23:31.880000Z",
          "director": "George Lucas",
          "edited": "2014-12-20T19:49:45.256000Z",
          "episode_id": 4,
          "opening_crawl": "It is a period of civil war.
      
          "planets": Array [
                     ],
          "title": "A New Hope",
        },
        Object {
          "characters": Array [
            "http://swapi.dev/api/people/1/",
            "http://swapi.dev/api/people/2/",
            "http://swapi.dev/api/people/3/",
            "http://swapi.dev/api/people/4/",
            "http://swapi.dev/api/people/5/",
            "http://swapi.dev/api/people/10/",
            "http://swapi.dev/api/people/13/",
            "http://swapi.dev/api/people/14/",
            "http://swapi.dev/api/people/18/",
            "http://swapi.dev/api/people/20/",
            "http://swapi.dev/api/people/21/",
            "http://swapi.dev/api/people/22/",
            "http://swapi.dev/api/people/23/",
            "http://swapi.dev/api/people/24/",
            "http://swapi.dev/api/people/25/",
            "http://swapi.dev/api/people/26/",
          ],
          "created": "2014-12-12T11:26:24.656000Z",
          "director": "Irvin Kershner",
          "edited": "2014-12-15T13:07:53.386000Z",
          "episode_id": 5,
          "opening_crawl": "It is a dark time for the
      Rebellion. Although the Death
      Star has been destroyed,
      Imperial troops have driven the
      Rebel forces from their hidden
      base and pursued them across
      the galaxy.
      
      Evading the dreaded Imperial
      Starfleet, a group of freedom
      fighters led by Luke Skywalker
      has established a new secret
      base on the remote ice world
      of Hoth.
      
      The evil lord Darth Vader,
      obsessed with finding young
      Skywalker, has dispatched
      thousands of remote probes into
      the far reaches of space....",
          "planets": Array [
            "http://swapi.dev/api/planets/4/",
            "http://swapi.dev/api/planets/5/",
            "http://swapi.dev/api/planets/6/",
            "http://swapi.dev/api/planets/27/",
          ],
          "producer": "Gary Kurtz, Rick McCallum",
          "release_date": "1980-05-17",
          "species": Array [
            "http://swapi.dev/api/species/1/",
            "http://swapi.dev/api/species/2/",
            "http://swapi.dev/api/species/3/",
            "http://swapi.dev/api/species/6/",
            "http://swapi.dev/api/species/7/",
          ],
          "starships": Array [
            "http://swapi.dev/api/starships/3/",
            "http://swapi.dev/api/starships/10/",
            "http://swapi.dev/api/starships/11/",
            "http://swapi.dev/api/starships/12/",
            "http://swapi.dev/api/starships/15/",
            "http://swapi.dev/api/starships/17/",
            "http://swapi.dev/api/starships/21/",
            "http://swapi.dev/api/starships/22/",
            "http://swapi.dev/api/starships/23/",
          ],
          "title": "The Empire Strikes Back",
          "url": "http://swapi.dev/api/films/2/",
          "vehicles": Array [
            "http://swapi.dev/api/vehicles/8/",
            "http://swapi.dev/api/vehicles/14/",
            "http://swapi.dev/api/vehicles/16/",
            "http://swapi.dev/api/vehicles/18/",
            "http://swapi.dev/api/vehicles/19/",
            "http://swapi.dev/api/vehicles/20/",
          ],
        },
        Object {  
          "title": "Return of the Jedi",
          
          ],
        },
        Object {
          "characters": Array [
            "http://swapi.dev/api/people/2/",
            "http://swapi.dev/api/people/3/",
            "http://swapi.dev/api/people/10/",
            "http://swapi.dev/api/people/11/",
            "http://swapi.dev/api/people/16/",
            "http://swapi.dev/api/people/20/",
            "http://swapi.dev/api/people/21/",
            "http://swapi.dev/api/people/32/",
            "http://swapi.dev/api/people/33/",
            "http://swapi.dev/api/people/34/",
            "http://swapi.dev/api/people/35/",
            "http://swapi.dev/api/people/36/",
            "http://swapi.dev/api/people/37/",
            "http://swapi.dev/api/people/38/",
            "http://swapi.dev/api/people/39/",
            "http://swapi.dev/api/people/40/",
            "http://swapi.dev/api/people/41/",
            "http://swapi.dev/api/people/42/",
            "http://swapi.dev/api/people/43/",
            "http://swapi.dev/api/people/44/",
            "http://swapi.dev/api/people/46/",
            "http://swapi.dev/api/people/47/",
            "http://swapi.dev/api/people/48/",
            "http://swapi.dev/api/people/49/",
            "http://swapi.dev/api/people/50/",
            "http://swapi.dev/api/people/51/",
            "http://swapi.dev/api/people/52/",
            "http://swapi.dev/api/people/53/",
            "http://swapi.dev/api/people/54/",
            "http://swapi.dev/api/people/55/",
            "http://swapi.dev/api/people/56/",
            "http://swapi.dev/api/people/57/",
            "http://swapi.dev/api/people/58/",
            "http://swapi.dev/api/people/59/",
          ], */