export const VerseData = [

    {   Key: "00001",
        Collection: "Strength",
        Book: "Philippians", 
        Chapter: "4",
        V: [13],
        Version: "WEB",
        Verse: "I can do all things through Christ, who strengthens me.",
        Personalise: "I can do all things through Christ, who strengthens me.",
        Display: true,
        Audio: "001_all_things.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00002", 
        Collection: "Identity",
        Book: "Galatians", 
        Chapter: "2",
        V: [20],
        Version: "WEB",
        Verse: "I have been crucified with Christ, and it is no longer I who live, but Christ lives in me. That life which I now live in the flesh, I live by faith in the Son of God, who loved me, and gave himself up for me.",
        Personalise: "I have been crucified with Christ, and it is no longer I who live, but Christ lives in me. That life which I now live in the flesh, I live by faith in the Son of God, who loved me, and gave himself up for me.",
        Display: true,
        Audio: "002_crucified.mp3",
        Deleteable: false,
        Favourite: false,
    },
    
    {   Key: "00003", 
        Collection: "Blessing",
        Book: "Romans", 
        Chapter: "8",
        V: [28],
        Version: "WEB",
        Verse: "We know that all things work together for good for those who love God, for those who are called according to his purpose.",
        Personalise: "I know that all things work together for my good.",
        Display: true,
        Audio: "003_work_together.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00004", 
        Collection: "Identity",
        Book: "Romans", 
        Chapter: "8",
        V: [31],
        Version: "WEB",
        Verse: "What then shall we say about these things? If God is for us, who can be against us?",
        Personalise: "God is for me so who can be against me?",
        Display: true,
        Audio: "004_god_is_for_you.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00005",
        Collection: "Identity",
        Book: "2 Corinthians", 
        Chapter: "5",
        V: [17],
        Version: "WEB",
        Verse: "Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.",
        Personalise: "I am a new creation in Christ.",
        Display: true,
        Audio: "005_new_creation.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00006", 
        Collection: "Salvation",
        Book: "Ephesians", 
        Chapter: "2",
        V: [5,6],
        Version: "WEB",
        Verse: "[God] even when we were dead through our trespasses, made us alive together with Christ — by grace you have been saved — and raised us up with him, and made us to sit with him in the heavenly places in Christ Jesus.",
        Personalise: "I have been made alive together with Christ. I am saved by grace. I am seated in heavenly places in Christ Jesus.",
        Display: true,
        Audio: "006_alive_with_christ.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00007", 
        Collection: "Strength",
        Book: "2 Timothy", 
        Chapter: "1",
        V: [7],
        Version: "WEB",
        Verse: "For God didn’t give us a spirit of fear, but of power, love, and self-control.",
        Personalise: "God has not given me the spirit of fear, but of power, and of love, and of self-control.",
        Display: true,
        Audio: "007_spirit_of_fear.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00008", 
        Collection: "Healing",
        Book: "1 Peter", 
        Chapter: "2",
        V: [24],
        Version: "WEB",
        Verse: "He himself bore our sins in his body on the tree, that we, having died to sins, might live to righteousness. You were healed by his wounds.",
        Personalise: "He bore my sins in His body, so that I might live for righteousness. By His wounds I am healed.",
        Display: true,
        Audio: "008_wounds.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00009", 
        Collection: "Provision",
        Book: "Matthew", 
        Chapter: "6",
        V: [33],
        Version: "WEB",
        Verse: "But seek first God’s Kingdom and his righteousness; and all these things will be given to you as well.",
        Personalise: "I seek first God's Kingdom and His righteousness; and everything I need is given unto me.",
        Display: true,
        Audio: "009_seek_first.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00010", 
        Collection: "Victory",
        Book: "Joshua", 
        Chapter: "1",
        V: [3,5],
        Version: "WEB",
        Verse: "I have given you every place that the sole of your foot will tread on, as I told Moses. No man will be able to stand before you all the days of your life. As I was with Moses, so I will be with you. I will not fail you nor forsake you.",
        Personalise: "You will give me every place where I set my foot. Nothing will be able to stand against me all the days of my life for You are with me. You will never fail me nor forsake me.",
        Display: true,
        Audio: "010_set_foot.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00011", 
        Collection: "Victory",
        Book: "1 John", 
        Chapter: "2",
        V: [14],
        Version: "WEB",
        Verse: "I have written to you, young men, because you are strong, and the word of God remains in you, and you have overcome the evil one.",
        Personalise: "I am strong. The word of God abides in me. I have overcome the wicked one.",
        Display: true,
        Audio: "011_are_strong.mp3",
        Deleteable: false,
        Favourite: false,
    },


    {   Key: "00012", 
        Collection: "Victory",
        Book: "1 John", 
        Chapter: "4",
        V: [4],
        Version: "WEB",
        Verse: "You are of God, little children, and have overcome them; because greater is he who is in you than he who is in the world.",
        Personalise: "Greater is He that is in me, than he who is in the world.",
        Display: true,
        Audio: "012_greater.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00013", 
        Collection: "Victory",
        Book: "Romans", 
        Chapter: "8",
        V: [37],
        Version: "WEB",
        Verse: "No, in all these things, we are more than conquerors through him who loved us.",
        Personalise: "In all things I am more than a conqueror through Him that loves me.",
        Display: true,
        Audio: "013_conquerors.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00014", 
        Collection: "Victory",
        Book: "Romans", 
        Chapter: "5",
        V: [17],
        Version: "WEB",
        Verse: "For if by the trespass of the one, death reigned through the one; so much more will those who receive the abundance of grace and of the gift of righteousness reign in life through the one, Jesus Christ.",
        Personalise: "I receive the abundance of grace and the gift of righteousness and I reign in life through Jesus Christ.",
        Display: true,
        Audio: "014_reign_in_life.mp3",
        Deleteable: false,
        Favourite: false,
    },
    
    {   Key: "00015", 
        Collection: "Blessing",
        Book: "Numbers", 
        Chapter: "6",
        V: [24,25,26],
        Version: "KJV",
        Verse: "The Lord bless thee, and keep thee: The Lord make his face shine upon thee, and be gracious unto thee: The Lord lift up his countenance upon thee, and give thee peace.",
        Personalise: "The Lord blesses me, and keeps me: The Lord makes his face shine upon me, and is gracious to me: The Lord has lifted up his countenance upon me, and has given me peace.",
        Display: true,
        Audio: "015_lord_bless_you.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00016", 
        Collection: "Blessing",
        Book: "Ephesians", 
        Chapter: "1",
        V: [3],
        Version: "WEB",
        Verse: "Blessed be the God and Father of our Lord Jesus Christ, who has blessed us with every spiritual blessing in the heavenly places in Christ.",
        Personalise: "I am blessed with every blessing in heavenly places.",
        Display: true,
        Audio: "016_heavenly_places.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00017", 
        Collection: "Protection",
        Book: "Psalms", 
        Chapter: "91",
        V: [1,2],
        Version: "WEB",
        Verse: "He who dwells in the secret place of the Most High, will rest in the shadow of the Almighty. I will say of the Lord, “He is my refuge and my fortress; my God, in whom I trust.",
        Personalise: "I dwell in the secret place of the Most High and abide under the shadow of the Almighty. He is my refuge and fortress. In my God I trust.",
        Display: true,
        Audio: "017_secret_place.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00018", 
        Collection: "Protection",
        Book: "Psalms", 
        Chapter: "91",
        V: [10,11],
        Version: "WEB",
        Verse: "No evil shall happen to you, neither shall any plague come near your dwelling. For he will put his angels in charge of you, to guard you in all your ways.",
        Personalise: "No evil shall befall me, neither shall any plague come near my dwelling. You give your angels charge over me, to guard me in all my ways.",
        Display: true,
        Audio: "018_no_evil.mp3",
        Deleteable: false,
        Favourite: false,
    },


    {   Key: "00019", 
        Collection: "Protection",
        Book: "2 Thessalonians", 
        Chapter: "3",
        V: [3],
        Version: "WEB",
        Verse: "But the Lord is faithful, who will establish you and guard you from the evil one.",
        Personalise: "The Lord is faithful, he establishes me and guards me from the evil one.",
        Display: true,
        Audio: "019_lord_is_faithful.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00020", 
        Collection: "Healing",
        Book: "Psalms", 
        Chapter: "103",
        V: [2,3],
        Version: "WEB",
        Verse: "Praise the Lord, my soul, and don’t forget all his benefits, who forgives all your sins, who heals all your diseases.",
        Personalise: "Praise the Lord, my soul, and don’t forget all his benefits, He forgives all my sins, He heals all my diseases.",
        Display: true,
        Audio: "020_heals_all.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00021", 
        Collection: "Authority",
        Book: "Matthew", 
        Chapter: "10",
        V: [8],
        Version: "WEB",
        Verse: "Heal the sick, cleanse the lepers, and cast out demons. Freely you received, so freely give.",
        Personalise: "I have authority in Jesus' name to heal the sick, cleanse the lepers, and cast out demons. Freely I received, so freely I give.",
        Display: true,
        Audio: "021_freely_give.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00022", 
        Collection: "Authority",
        Book: "Luke", 
        Chapter: "10",
        V: [19],
        Version: "WEB",
        Verse: "Behold, I give you authority to tread on serpents and scorpions, and over all the power of the enemy. Nothing will in any way hurt you.",
        Personalise: "I have authority to tread on serpents and scorpions, and over all the power of the enemy. Nothing will in any way hurt me.",
        Display: true,
        Audio: "022_nothing_will_hurt.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00023", 
        Collection: "Authority",
        Book: "Philippians", 
        Chapter: "2",
        V: [9,10],
        Version: "WEB",
        Verse: "Therefore God also highly exalted him, and gave to him the name which is above every name, that at the name of Jesus every knee should bow, of those in heaven, those on earth, and those under the earth.",
        Personalise: "I speak the name of Jesus, the name above every name, at the name of Jesus every knee shall bow, in heaven, on earth, and under the earth.",
        Display: true,
        Audio: "023_name_of_jesus.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00024", 
        Collection: "Healing",
        Book: "Romans", 
        Chapter: "8",
        V: [11],
        Version: "WEB",
        Verse: "But if the Spirit of him who raised up Jesus from the dead dwells in you, he who raised up Christ Jesus from the dead will also give life to your mortal bodies through his Spirit who dwells in you.",
        Personalise: "The Spirit of him who raised up Jesus from the dead dwells in me. He who raised up Christ Jesus from the dead also gives life to my body.",
        Display: true,
        Audio: "024_life_to_your_body.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00025", 
        Collection: "Strength",
        Book: "Deuteronomy", 
        Chapter: "33",
        V: [25],
        Version: "WEB",
        Verse: "Your bars will be iron and bronze. As your days, so your strength will be.",
        Personalise: "My strength will equal my days.",
        Display: true,
        Audio: "025_strength_equal_days.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00026", 
        Collection: "Identity",
        Book: "2 Corinthians", 
        Chapter: "5",
        V: [21],
        Version: "WEB",
        Verse: "For him who knew no sin he made to be sin on our behalf; so that in him we might become the righteousness of God.",
        Personalise: "In Christ, I am the righteousness of God.",
        Display: true,
        Audio: "026_rigtheousness_of_god.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00027", 
        Collection: "Identity",
        Book: "Colossians", 
        Chapter: "1",
        V: [22],
        Version: "WEB",
        Verse: "[Now] he has reconciled in the body of his flesh through death, to present you holy and without defect and blameless before him.",
        Personalise: "I am holy, without defect and blameless before Him.",
        Display: true,
        Audio: "027_blameless_before_him.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00028", 
        Collection: "Identity",
        Book: "1 Peter", 
        Chapter: "1",
        V: [23],
        Version: "WEB",
        Verse: "[You are] born again, not of corruptible seed, but of incorruptible, through the word of God, which lives and remains forever.",
        Personalise: "I am born again through the ever-living word of God.",
        Display: true,
        Audio: "028_born_again.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00029", 
        Collection: "Salvation",
        Book: "Colossians", 
        Chapter: "1",
        V: [13,14],
        Version: "WEB",
        Verse: "[God] delivered us out of the power of darkness, and translated us into the Kingdom of the Son of his love, in whom we have our redemption, the forgiveness of our sins.",
        Personalise: "I am delivered out of the power of darkness, and translated into the Kingdom of the Son of God's love. In Him I have redemption, the forgiveness of all my sins.",
        Display: true,
        Audio: "029_delivered.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00030", 
        Collection: "Salvation",
        Book: "Romans", 
        Chapter: "12",
        V: [2],
        Version: "WEB",
        Verse: "Don’t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.",
        Personalise: "I am being transformed by the renewing of my mind, so that I may prove what is the good, well-pleasing, and perfect will of God for my life.",
        Display: true,
        Audio: "030_transformed.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00031", 
        Collection: "Identity",
        Book: "John", 
        Chapter: "14",
        V: [20],
        Version: "WEB",
        Verse: "In that day you will know that I am in my Father, and you in me, and I in you.",
        Personalise: "Jesus is in the Father, I am in Him, and He is in me.",
        Display: true,
        Audio: "031_in_the_father.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00032", 
        Collection: "Victory",
        Book: "1 John", 
        Chapter: "5",
        V: [4],
        Version: "WEB",
        Verse: "For whatever is born of God overcomes the world. This is the victory that has overcome the world: your faith.",
        Personalise: "I am born of God and overcome the world. The victory that has overcome the world is my faith.",
        Display: true,
        Audio: "032_overcome.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00033", 
        Collection: "Identity",
        Book: "1 Corinthians", 
        Chapter: "2",
        V: [16],
        Version: "WEB",
        Verse: "“For who has known the mind of the Lord, that he should instruct him?” But we have Christ’s mind.",
        Personalise: "I have the mind of Christ.",
        Display: true,
        Audio: "033_mind.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00034", 
        Collection: "Blessing",
        Book: "2 Corinthians", 
        Chapter: "13",
        V: [14],
        Version: "WEB",
        Verse: "The grace of the Lord Jesus Christ, God’s love, and the fellowship of the Holy Spirit be with you all. Amen.",
        Personalise: "The grace of the Lord Jesus Christ, God’s love, and the fellowship of the Holy Spirit are with me.",
        Display: true,
        Audio: "034_fellowship.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00035", 
        Collection: "Provision",
        Book: "Hebrews", 
        Chapter: "4",
        V: [16],
        Version: "WEB",
        Verse: "Let’s therefore draw near with boldness to the throne of grace, that we may receive mercy and may find grace for help in time of need.",
        Personalise: "I draw near with boldness to the throne of grace, so that I may receive mercy and find grace for help in time of need.",
        Display: true,
        Audio: "035_draw_near.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00036", 
        Collection: "Prayer",
        Book: "John", 
        Chapter: "15",
        V: [7],
        Version: "WEB",
        Verse: "If you remain in me, and my words remain in you, you will ask whatever you desire, and it will be done for you.",
        Personalise: "I remain in Jesus, and His words remain in me, I ask whatever I desire, and it is done for me.",
        Display: true,
        Audio: "036_remain.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00037", 
        Collection: "Healing",
        Book: "Psalms", 
        Chapter: "107",
        V: [20],
        Version: "WEB",
        Verse: "He sends his word, and heals them, and delivers them from their graves.",
        Personalise: "God has sent His Word and healed me. He has delivered me from the grave.",
        Display: true,
        Audio: "037_sent_his_word.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00038", 
        Collection: "Protection",
        Book: "Psalms", 
        Chapter: "121",
        V: [7],
        Version: "KJV",
        Verse: "The Lord shall preserve thee from all evil: he shall preserve thy soul.",
        Personalise: "The Lord shall preserve me from all evil: he shall preserve my soul.",
        Display: true,
        Audio: "038_preserve.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00039", 
        Collection: "Prayer",
        Book: "1 John", 
        Chapter: "5",
        V: [14,15],
        Version: "WEB",
        Verse: "This is the boldness which we have toward him, that if we ask anything according to his will, he listens to us. And if we know that he listens to us, whatever we ask, we know that we have the petitions which we have asked of him.",
        Personalise: "This is the boldness which I have toward Him, that if I ask anything according to his will, He hears me. And knowing that he hears me, whatever I ask, I know that I have the petitions which I have asked of Him.",
        Display: true,
        Audio: "039_boldness.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00040", 
        Collection: "Prayer",
        Book: "Mark", 
        Chapter: "11",
        V: [24],
        Version: "WEB",
        Verse: "Therefore I tell you, all things whatever you pray and ask for, believe that you have received them, and you shall have them.",
        Personalise: "All things whatever I pray and ask for, I believe that I have received them, and I shall have them.",
        Display: true,
        Audio: "040_believe.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00041", 
        Collection: "Prayer",
        Book: "Matthew", 
        Chapter: "21",
        V: [22],
        Version: "WEB",
        Verse: "All things, whatever you ask in prayer, believing, you will receive.",
        Personalise: "All things, whatever I ask in prayer, believing, I will receive.",
        Display: true,
        Audio: "041_ask_believing.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00042", 
        Collection: "Salvation",
        Book: "Philippians", 
        Chapter: "2",
        V: [13],
        Version: "WEB",
        Verse: "For it is God who works in you both to will and to work, for his good pleasure.",
        Personalise: "God is working in me to will and to do according to His good pleasure.",
        Display: true,
        Audio: "042_working_in_you.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00043", 
        Collection: "Prayer",
        Book: "Matthew", 
        Chapter: "7",
        V: [8],
        Version: "WEB",
        Verse: "For everyone who asks receives. He who seeks finds. To him who knocks it will be opened.",
        Personalise: "When I ask I receive. When I seek I find. When I knock the door is opened for me.",
        Display: true,
        Audio: "043_seek.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00044", 
        Collection: "Authority",
        Book: "Acts", 
        Chapter: "1",
        V: [8],
        Version: "WEB",
        Verse: "But you will receive power when the Holy Spirit has come upon you.",
        Personalise: "I have received the Holy Spirit and power.",
        Display: true,
        Audio: "044_receive_power.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00045", 
        Collection: "Strength",
        Book: "Philippians", 
        Chapter: "4",
        V: [13],
        Version: "WEB",
        Verse: "I can do all things through Christ, who strengthens me.",
        Personalise: "I can do all things through Christ, who strengthens me.",
        Display: true,
        Audio: "045_do_all_things.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00046", 
        Collection: "Strength",
        Book: "2 Corinthians", 
        Chapter: "12",
        V: [9],
        Version: "WEB",
        Verse: "He has said to me, “My grace is sufficient for you, for my power is made perfect in weakness.” Most gladly therefore I will rather glory in my weaknesses, that the power of Christ may rest on me.",
        Personalise: "The Lord's grace is sufficient for me, for His power is made perfect in my weakness. I glory in my weaknesses, that the power of Christ may rest on me.",
        Display: true,
        Audio: "046_grace_sufficient.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00047", 
        Collection: "Healing",
        Book: "John", 
        Chapter: "6",
        V: [63],
        Version: "WEB",
        Verse: "It is the spirit who gives life. The flesh profits nothing. The words that I speak to you are spirit, and are life.",
        Personalise: "When I speak the words of God they are Spirit and life.",
        Display: true,
        Audio: "047_spirit_and_life.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00048", 
        Collection: "Healing",
        Book: "Matthew", 
        Chapter: "8",
        V: [16,17],
        Version: "WEB",
        Verse: "[Jesus] healed all who were sick, that it might be fulfilled which was spoken through Isaiah the prophet, saying, “He took our infirmities and bore our diseases.”",
        Personalise: "Jesus heals all my sickness. He took up my infirmities and bore my diseases.",
        Display: true,
        Audio: "048_heals_all.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00049", 
        Collection: "Identity",
        Book: "Colossians", 
        Chapter: "1",
        V: [27],
        Version: "WEB",
        Verse: "...God was pleased to make known what are the riches of the glory of this mystery among the Gentiles, which is Christ in you, the hope of glory.",
        Personalise: "Christ is in me - the hope of glory.",
        Display: true,
        Audio: "049_christ_in_you.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00050", 
        Collection: "Identity",
        Book: "Colossians", 
        Chapter: "2",
        V: [9,10],
        Version: "WEB",
        Verse: "For in him all the fullness of the Deity dwells bodily, and in him you are made full, who is the head of all principality and power.",
        Personalise: "I am made full in Christ - the head of all principality and power.",
        Display: true,
        Audio: "050_full.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00051", 
        Collection: "Identity",
        Book: "Colossians", 
        Chapter: "3",
        V: [3,4],
        Version: "WEB",
        Verse: "For you died, and your life is hidden with Christ in God. When Christ, our life, is revealed, then you will also be revealed with him in glory.",
        Personalise: "I died, and my life is hidden with Christ in God. When Christ, my life, is revealed, then I will also be revealed with Him in glory.",
        Display: true,
        Audio: "051_you_died.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00052", 
        Collection: "Identity",
        Book: "Colossians", 
        Chapter: "3",
        V: [9,10],
        Version: "WEB",
        Verse: "...You have put off the old man with his doings, and have put on the new man, who is being renewed in knowledge after the image of his Creator.",
        Personalise: "I have put off the old man and have put on the new man, who is being renewed in knowledge after the image of his Creator.",
        Display: true,
        Audio: "052_new_man.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00053", 
        Collection: "Salvation",
        Book: "Romans", 
        Chapter: "6",
        V: [4],
        Version: "WEB",
        Verse: "We were buried therefore with him through baptism into death, that just as Christ was raised from the dead through the glory of the Father, so we also might walk in newness of life.",
        Personalise: "I was buried with Christ through baptism into death, so that just as Christ was raised from the dead through the glory of the Father, I also might walk in newness of life.",
        Display: true,
        Audio: "053_buried_with_christ.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00054", 
        Collection: "Salvation",
        Book: "Romans", 
        Chapter: "6",
        V: [18],
        Version: "WEB",
        Verse: "Being made free from sin, you became bondservants of righteousness.",
        Personalise: "I am set free from sin, and have become a bondservant of righteousness.",
        Display: true,
        Audio: "054_set_free.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00055", 
        Collection: "Salvation",
        Book: "Romans", 
        Chapter: "7",
        V: [4],
        Version: "WEB",
        Verse: "Therefore my brothers, you also were made dead to the law through the body of Christ, that you would be joined to another, to him who was raised from the dead, that we might produce fruit to God.",
        Personalise: "I am dead to the law through the body of Christ, and I am now joined to Him who was raised from the dead.",
        Display: true,
        Audio: "055_dead_to_law.mp3",
        Deleteable: false,
        Favourite: false,
    },


    {   Key: "00056", 
        Collection: "Authority",
        Book: "Mark", 
        Chapter: "16",
        V: [17,18],
        Version: "WEB",
        Verse: "These signs will accompany those who believe: in my name they will cast out demons; they will speak with new languages; they will take up serpents; and if they drink any deadly thing, it will in no way hurt them; they will lay hands on the sick, and they will recover.",
        Personalise: "In Jesus' name I will cast out demons and lay hands on the sick, and they will recover.",
        Display: true,
        Audio: "056_signs.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00057", 
        Collection: "Salvation",
        Book: "1 John", 
        Chapter: "3",
        V: [2],
        Version: "WEB",
        Verse: "Beloved, now we are children of God. It is not yet revealed what we will be; but we know that when he is revealed, we will be like him; for we will see him just as he is.",
        Personalise: "Now I am a child of God. When He is revealed, I will be like Him, for I will see Him, as He is.",
        Display: true,
        Audio: "057_like_him.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00058", 
        Collection: "Loved",
        Book: "Zephaniah", 
        Chapter: "3",
        V: [17],
        Version: "WEB",
        Verse: "The Lord, your God, is among you, a mighty one who will save. He will rejoice over you with joy. He will calm you in his love. He will rejoice over you with singing.",
        Personalise: "My God is with me, a mighty One who will save. He rejoices over me with great delight. He calms me in His love. He rejoices over me with singing.",
        Display: true,
        Audio: "058_rejoices_over_you.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00059", 
        Collection: "Loved",
        Book: "Psalms", 
        Chapter: "139",
        V: [1,2],
        Version: "WEB",
        Verse: `Lord, you have searched me,\nand you know me.\nYou know my sitting down\nand my rising up.\nYou perceive my thoughts from afar.`,
        Personalise: `Lord God, you have searched me,\nand you know me.\nYou know my sitting down\nand my rising up.\nYou perceive my thoughts from afar.`,
        Display: true,
        Audio: "059_searched_you.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00060", 
        Collection: "Loved",
        Book: "Psalms", 
        Chapter: "139",
        V: [3,4,5],
        Version: "WEB",
        Verse: "You search out my path and my lying down,\nand are acquainted with all my ways.\nFor there is not a word on my tongue,\nbut, behold, Lord, you know it altogether.\nYou hem me in behind and before.\nYou laid your hand on me.",
        Personalise: "God, you have searched out my path and my lying down,\nand You are acquainted with all my ways.\nFor there is not a word on my tongue,\nbut, You know it altogether.\nYou have hemmed me in behind and before.\nYou have laid your hand on me.",
        Display: true,
        Audio: "060_knows_your_ways.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00061", 
        Collection: "Loved",
        Book: "Psalms", 
        Chapter: "139",
        V: [13,14],
        Version: "WEB",
        Verse: "For you formed my inmost being.\nYou knit me together in my mother’s womb.\nI will give thanks to you,\nfor I am fearfully and wonderfully made.\nYour works are wonderful.\nMy soul knows that very well.",
        Personalise: "For you Lord God formed my inmost being.\nYou knit me together in my mother’s womb.\nI will give thanks to you,\nfor I am fearfully and wonderfully made.\nYour works are wonderful.",
        Display: true,
        Audio: "061_fearfully.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00062", 
        Collection: "Loved",
        Book: "Psalms", 
        Chapter: "139",
        V: [17,18],
        Version: "WEB",
        Verse: "How precious to me are your thoughts, God!\nHow vast is their sum!\nIf I would count them, they are more in number than the sand.\nWhen I wake up, I am still with you.",
        Personalise: "How precious to me are your thoughts, God!\nHow vast is their sum!\nIf I would count them, they are more in number than the sand.\nWhen I wake up, I am still with you.",
        Display: true,
        Audio: "062_thoughts.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00063", 
        Collection: "Salvation",
        Book: "Romans", 
        Chapter: "8",
        V: [1],
        Version: "WEB",
        Verse: "There is therefore now no condemnation to those who are in Christ Jesus, who don’t walk according to the flesh, but according to the Spirit.",
        Personalise: "There is now no condemnation for me in Christ Jesus. I do not walk according to the flesh but according to the Spirit.",
        Display: true,
        Audio: "063_no_condemnation.mp3",
        Deleteable: false,
        Favourite: false,
    },
    
    
    {   Key: "00064", 
        Collection: "Loved",
        Book: "Romans", 
        Chapter: "8",
        V: [14,15],
        Version: "WEB",
        Verse: `For as many as are led by the Spirit of God, these are children of God. For you didn’t receive the spirit of bondage again to fear, but you received the Spirit of adoption, by whom we cry, "Abba! Father!"`,
        Personalise: `I am led by the Spirit of God and I am a child of God. I have not received the spirit of bondage again to fear but I have received the Spirit of adoption, by Him I cry, "Abba! Father!"`,
        Display: true,
        Audio: "064_abba.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00065", 
        Collection: "Identity",
        Book: "Romans", 
        Chapter: "8",
        V: [16,17],
        Version: "WEB",
        Verse: "The Spirit himself testifies with our spirit that we are children of God; and if children, then heirs: heirs of God and joint heirs with Christ, if indeed we suffer with him, that we may also be glorified with him.",
        Personalise: "I am a child of God. An heir of God and a joint heir with Christ.",
        Display: true,
        Audio: "065_heir.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00066", 
        Collection: "Identity",
        Book: "1 Corinthians", 
        Chapter: "6",
        V: [19,20],
        Version: "WEB",
        Verse: "Or don’t you know that your body is a temple of the Holy Spirit who is in you, whom you have from God? You are not your own, for you were bought with a price. Therefore glorify God in your body and in your spirit, which are God’s.",
        Personalise: "My body is a temple of the Holy Spirit, who is in me. I am not my own, I was bought with a price.",
        Display: true,
        Audio: "066_temple.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00067", 
        Collection: "Apostolic Prayers",
        Book: "Colossians", 
        Chapter: "1",
        V: [9,10,11],
        Version: "WEB",
        Verse: "[May you] ...be filled with the knowledge of his will in all spiritual wisdom and understanding, that you may walk worthily of the Lord, to please him in all respects, bearing fruit in every good work and increasing in the knowledge of God, strengthened with all power, according to the might of his glory, for all endurance and perseverance with joy.",
        Personalise: "Father God, fill me with the knowledge of Your will in all spiritual wisdom and understanding, so that I may walk worthily of the Lord, and please Him in all respects, bearing fruit in every good work and increasing in the knowledge of You, strengthened with all power, according to the might of Your glory, for all endurance and perseverance with joy.",
        Display: true,
        Audio: "067_fill_you.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00068", 
        Collection: "Apostolic Prayers",
        Book: "Ephesians", 
        Chapter: "3",
        V: [16,17,18,19],
        Version: "WEB",
        Verse: "[May you] ...be strengthened with power through his Spirit in the inner person, that Christ may dwell in your hearts through faith, to the end that you, being rooted and grounded in love, may be strengthened to comprehend with all the saints what is the width and length and height and depth, and to know Christ’s love which surpasses knowledge, that you may be filled with all the fullness of God.",
        Personalise: "Father God, strengthen me with power through Your Spirit in my inner person, so that Christ may dwell in my heart through faith, to the end that I, being rooted and grounded in love, may be strengthened to comprehend with all the saints what is the width and length and height and depth, and to know Christ’s love which surpasses knowledge, that I may be filled with all the fullness of God.",
        Display: true,
        Audio: "068_fullness.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00069", 
        Collection: "Protection",
        Book: "Psalms", 
        Chapter: "3",
        V: [3],
        Version: "WEB",
        Verse: "But you, Lord, are a shield around me,\nmy glory, and the one who lifts up my head.",
        Personalise: "But you, O God, are a shield around me,\nmy glory, and the one who lifts up my head.",
        Display: true,
        Audio: "069_lifter.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00070", 
        Collection: "Apostolic Prayers",
        Book: "Ephesians", 
        Chapter: "1",
        V: [17,18,19],
        Version: "WEB",
        Verse: "that the God of our Lord Jesus Christ, the Father of glory, may give to you a spirit of wisdom and revelation in the knowledge of him, having the eyes of your hearts enlightened, that you may know what is the hope of his calling, and what are the riches of the glory of his inheritance in the saints, and what is the exceeding greatness of his power toward us who believe, according to that working of the strength of his might.",
        Personalise: "Father, give me a spirit of wisdom and revelation in the knowledge of You, enlighten the eyes of my heart, that I may know the hope of Your calling, and the riches of the glory of Your inheritance in the saints, and the exceeding greatness of Your power toward those who believe.",
        Display: true,
        Audio: "070_revelation.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00071", 
        Collection: "Apostolic Prayers",
        Book: "Philippians", 
        Chapter: "1",
        V: [9,10,11],
        Version: "WEB",
        Verse: "This I pray, that your love may abound yet more and more in knowledge and all discernment, so that you may approve the things that are excellent, that you may be sincere and without offense to the day of Christ, being filled with the fruits of righteousness, which are through Jesus Christ, to the glory and praise of God.",
        Personalise: "Father, may my love abound more and more in knowledge and all discernment, so that I may approve the things that are excellent, and that I may be sincere and without offense to the day of Christ. May I be filled with the fruits of righteousness, through Jesus Christ, for Your glory and praise.",
        Display: true,
        Audio: "071_approve.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00072", 
        Collection: "Apostolic Prayers",
        Book: "Romans", 
        Chapter: "15",
        V: [5,6],
        Version: "WEB",
        Verse: "Now the God of perseverance and of encouragement grant you to be of the same mind with one another according to Christ Jesus, that with one accord you may with one mouth glorify the God and Father of our Lord Jesus Christ.",
        Personalise: "Father of perseverance and encouragement, let me be of the same mind with all believers according to Christ Jesus, that with one accord we may with one mouth glorify You, the God and Father of our Lord Jesus Christ.",
        Display: true,
        Audio: "072_god_of_encouragement.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00073", 
        Collection: "Apostolic Prayers",
        Book: "Romans", 
        Chapter: "15",
        V: [13],
        Version: "WEB",
        Verse: "Now may the God of hope fill you with all joy and peace in believing, that you may abound in hope, in the power of the Holy Spirit.",
        Personalise: "Father of hope, fill me with all joy and peace in believing, that I may abound in hope, in the power of the Holy Spirit.",
        Display: true,
        Audio: "073_god_of_hope.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00074", 
        Collection: "Apostolic Prayers",
        Book: "1 Thessalonians", 
        Chapter: "3",
        V: [12,13],
        Version: "WEB",
        Verse: "May the Lord make you to increase and abound in love toward one another, and toward all men, even as we also do toward you, to the end he may establish your hearts blameless in holiness before our God and Father at the coming of our Lord Jesus with all his saints.",
        Personalise: "Lord, make me increase and abound in love to everyone. And Lord, establish my heart blameless in holiness before my God and Father when You come with all Your saints.",
        Display: true,
        Audio: "074_establish.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00075", 
        Collection: "Identity",
        Book: "John", 
        Chapter: "10",
        V: [10],
        Version: "WEB",
        Verse: "The thief only comes to steal, kill, and destroy. I came that they may have life, and may have it abundantly.",
        Personalise: "Jesus came so that I may have life, and have it abundantly.",
        Display: true,
        Audio: "075_abundantly.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00076", 
        Collection: "Loved",
        Book: "John", 
        Chapter: "3",
        V: [16],
        Version: "WEB",
        Verse: "For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.",
        Personalise: "For God so loved me, that He gave His one and only Son, that by believing in Him I should not perish, but have eternal life.",
        Display: true,
        Audio: "076_for_god_so.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00077", 
        Collection: "Salvation",
        Book: "1 John", 
        Chapter: "5",
        V: [11],
        Version: "WEB",
        Verse: "The testimony is this, that God gave to us eternal life, and this life is in his Son.",
        Personalise: "God has given me eternal life, and this life is in his Son.",
        Display: true,
        Audio: "077_life_in_the_son.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00078", 
        Collection: "Salvation",
        Book: "John", 
        Chapter: "10",
        V: [28],
        Version: "WEB",
        Verse: "I give eternal life to them. They will never perish, and no one will snatch them out of my hand.",
        Personalise: "Jesus has given me eternal life. I will never perish, and no one will snatch me out of Jesus' hand.",
        Display: true,
        Audio: "078_snatch.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00079", 
        Collection: "Comfort",
        Book: "Isaiah", 
        Chapter: "41",
        V: [10],
        Version: "WEB",
        Verse: "Don’t you be afraid, for I am with you.\nDon’t be dismayed, for I am your God.\nI will strengthen you.\nYes, I will help you.\nYes, I will uphold you with the right hand of my righteousness.",
        Personalise: "I will not be afraid, for You are with me.\nI will not be distressed, for You are my God.\nYou will strengthen me.\nYou will help me.\nYou will uphold me with the right hand of your righteousness.",
        Display: true,
        Audio: "079_do_not_be_afraid.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00080", 
        Collection: "Comfort",
        Book: "Deuteronomy", 
        Chapter: "31",
        V: [6],
        Version: "WEB",
        Verse: "Be strong and courageous. Don’t be afraid or scared of them; for the Lord your God himself is who goes with you. He will not fail you nor forsake you.",
        Personalise: "I will be strong and courageous. I will not be afraid; for my God Himself is He who goes with me. He will not fail me nor forsake me.",
        Display: true,
        Audio: "080_be strong.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00081", 
        Collection: "Comfort",
        Book: "Psalms", 
        Chapter: "73",
        V: [26],
        Version: "WEB",
        Verse: "My flesh and my heart fails,\nbut God is the strength of my heart\nand my portion forever.",
        Personalise: "My flesh and my heart may fail,\nbut God is the strength of my heart\nand my portion forever.",
        Display: true,
        Audio: "081_heart_strength.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00082", 
        Collection: "Comfort",
        Book: "Psalms", 
        Chapter: "3",
        V: [3],
        Version: "WEB",
        Verse: "But you, Lord,\nare a shield around me,\nmy glory,\nand the one who lifts up my head.",
        Personalise: "But you, Lord,\nare a shield around me,\nmy glory,\nand the one who lifts up my head.",
        Display: true,
        Audio: "082_lifter.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00083", 
        Collection: "Comfort",
        Book: "Psalms", 
        Chapter: "27",
        V: [1],
        Version: "WEB",
        Verse: "The Lord is my light and my salvation.\nWhom shall I fear?\nThe Lord is the strength of my life.\nOf whom shall I be afraid?",
        Personalise: "The Lord is my light and my salvation.\nWhom shall I fear?\nThe Lord is the strength of my life.\nOf whom shall I be afraid?",
        Display: true,
        Audio: "083_whom_fear.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00084", 
        Collection: "Strength",
        Book: "Habakkuk", 
        Chapter: "3",
        V: [19],
        Version: "WEB",
        Verse: "The Lord, is my strength.\nHe makes my feet like deer’s feet,\nand enables me to go in high places.",
        Personalise: "The Lord, is my strength.\nHe makes my feet like deer’s feet,\nand enables me to walk upon the heights.",
        Display: true,
        Audio: "084_deers_feet.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00085", 
        Collection: "Victory",
        Book: "Deuteronomy", 
        Chapter: "20",
        V: [4],
        Version: "WEB",
        Verse: "...for the Lord your God is he who goes with you, to fight for you against your enemies, to save you.",
        Personalise: "God goes with me, to fight for me against my enemies, to save me.",
        Display: true,
        Audio: "085_fight_for_you.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00086", 
        Collection: "Protection",
        Book: "Zechariah", 
        Chapter: "2",
        V: [5],
        Version: "WEB",
        Verse: "'For I,' says the Lord, 'will be to her a wall of fire around it, and I will be the glory in the middle of her.'",
        Personalise: "The Lord is a wall of fire around me, and He is the glory in my midst.",
        Display: true,
        Audio: "086_wall_of_fire.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00087", 
        Collection: "Strength",
        Book: "Isaiah", 
        Chapter: "40",
        V: [29],
        Version: "WEB",
        Verse: "He gives power to the weak.\nHe increases the strength of him who has no might.",
        Personalise: "The Lord gives power to me when I am weak.\nHe increases my strength when I have no might.",
        Display: true,
        Audio: "087_weak.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00088", 
        Collection: "Comfort",
        Book: "Isaiah", 
        Chapter: "12",
        V: [2],
        Version: "WEB",
        Verse: "Behold, God is my salvation. I will trust, and will not be afraid; for God, the Lord, is my strength and song; and he has become my salvation.",
        Personalise: "Behold, God is my salvation. I will trust, and will not be afraid; for the Lord, is my strength and song; and he has become my salvation.",
        Display: true,
        Audio: "088_song.mp3",
        Deleteable: false,
        Favourite: false,
    },

    
    {   Key: "00089", 
        Collection: "Comfort",
        Book: "1 Peter", 
        Chapter: "5",
        V: [10],
        Version: "WEB",
        Verse: "But may the God of all grace, who called you to his eternal glory by Christ Jesus, after you have suffered a little while, perfect, establish, strengthen, and settle you.",
        Personalise: "The God of all grace, who has called me to His eternal glory by Christ Jesus, after I have suffered a little while, will perfect, establish, strengthen, and settle me.",
        Display: true,
        Audio: "089_suffer.mp3",
        Deleteable: false,
        Favourite: false,
    },
    
    
    {   Key: "00090", 
        Collection: "Comfort",
        Book: "2 Corinthians", 
        Chapter: "1",
        V: [3,4],
        Version: "WEB",
        Verse: "Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort; who comforts us in all our affliction, that we may be able to comfort those who are in any affliction, through the comfort with which we ourselves are comforted by God.",
        Personalise: "Blessed be the God and Father of my Lord Jesus Christ, He is the Father of mercies and God of all comfort; who comforts me in all my troubles, so that I may be able to comfort others who are in affliction.",
        Display: true,
        Audio: "090_any_affliction.mp3",
        Deleteable: false,
        Favourite: false,
    },
    
    
    {   Key: "00091", 
        Collection: "Comfort",
        Book: "Romans", 
        Chapter: "5",
        V: [3,4,5],
        Version: "WEB",
        Verse: "...We also rejoice in our sufferings, knowing that suffering produces perseverance; and perseverance, proven character; and proven character, hope: and hope doesn’t disappoint us, because God’s love has been poured into our hearts through the Holy Spirit who was given to us.",
        Personalise: "I rejoice in my sufferings, knowing that it is producing perseverance, character and hope: and hope doesn't disappoint because God’s love has been poured into my heart through the Holy Spirit.",
        Display: true,
        Audio: "091_character.mp3",
        Deleteable: false,
        Favourite: false,
    },
    
    
    {   Key: "00092", 
        Collection: "Comfort",
        Book: "Romans", 
        Chapter: "8",
        V: [18],
        Version: "WEB",
        Verse: "For I consider that the sufferings of this present time are not worthy to be compared with the glory which will be revealed toward us.",
        Personalise: "The sufferings of this present time are not worthy to be compared with the glory which will be revealed in me.",
        Display: true,
        Audio: "092_compared.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00093", 
        Collection: "Salvation",
        Book: "Romans", 
        Chapter: "8",
        V: [32],
        Version: "WEB",
        Verse: "He who didn’t spare his own Son, but delivered him up for us all, how would he not also with him freely give us all things?",
        Personalise: "God who didn’t spare his own Son, but delivered Him up for me, how would He not also with Him freely give me all things?",
        Display: true,
        Audio: "093_freely.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00094", 
        Collection: "Loved",
        Book: "Romans", 
        Chapter: "8",
        V: [38,39],
        Version: "WEB",
        Verse: "For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers, nor height, nor depth, nor any other created thing will be able to separate us from God’s love which is in Christ Jesus our Lord.",
        Personalise: "For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers, nor height, nor depth, nor any other created thing will be able to separate me from God’s love which is in Christ Jesus my Lord.",
        Display: true,
        Audio: "094_neither.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00095", 
        Collection: "Comfort",
        Book: "2 Corinthians", 
        Chapter: "4",
        V: [17],
        Version: "WEB",
        Verse: "For our light affliction, which is for the moment, works for us more and more exceedingly an eternal weight of glory...",
        Personalise: "My light affliction, which is but for the moment, is workings for me a far more exceeding and eternal weight of glory.",
        Display: true,
        Audio: "095_light_affliction.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00096", 
        Collection: "Blessing",
        Book: "Jeremiah", 
        Chapter: "17",
        V: [7,8],
        Version: "WEB",
        Verse: "Blessed is the man who trusts in the Lord, and whose confidence is in the Lord. For he will be as a tree planted by the waters, who spreads out its roots by the river, and will not fear when heat comes, but its leaf will be green, and will not be concerned in the year of drought. It won’t cease from yielding fruit.",
        Personalise: "I am blessed as I trust in the Lord, and put my confidence in Him. I will be like a tree planted by the waters, which does not fear when heat comes, but its leaves are always green, and it does not cease from yielding fruit.",
        Display: true,
        Audio: "096_tree.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00097", 
        Collection: "Comfort",
        Book: "Jeremiah", 
        Chapter: "29",
        V: [1],
        Version: "WEB",
        Verse: `"For I know the thoughts that I think toward you," says the Lord, "thoughts of peace, and not of evil, to give you hope and a future."`,
        Personalise: "God knows the plans He has for me. Plans of peace, not of evil, plans to give me a hope and a future.",
        Display: true,
        Audio: "097_plans.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00098", 
        Collection: "Provision",
        Book: "Philippians", 
        Chapter: "4",
        V: [19],
        Version: "WEB",
        Verse: "My God will supply every need of yours according to his riches in glory in Christ Jesus.",
        Personalise: "God will supply my every need according to His riches in glory in Christ Jesus.",
        Display: true,
        Audio: "098_supply.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00099", 
        Collection: "Healing",
        Book: "Exodus", 
        Chapter: "23",
        V: [25,26],
        Version: "WEB",
        Verse: "You shall serve the Lord your God, and he will bless your bread and your water, and I will take sickness away from among you. No one will miscarry or be barren in your land. I will fulfil the number of your days.",
        Personalise: "I serve the Lord my God, and He blesses my bread and my water, He has taken sickness away from me. No one in my household will miscarry or be barren. He will fulfil the number of my days.",
        Display: true,
        Audio: "099_no_miscarriage.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00100", 
        Collection: "Comfort",
        Book: "Psalms", 
        Chapter: "23",
        V: [1,2],
        Version: "WEB",
        Verse: "The Lord is my shepherd:\nI shall lack nothing.\nHe makes me lie down in green pastures.\nHe leads me beside still waters.",
        Personalise: "The Lord is my shepherd:\nI shall lack nothing.\nHe makes me lie down in green pastures.\nHe leads me beside still waters.",
        Display: true,
        Audio: "100_still_waters.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00101", 
        Collection: "Blessing",
        Book: "Psalms", 
        Chapter: "23",
        V: [5,6],
        Version: "WEB",
        Verse: "You prepare a table before me\nin the presence of my enemies.\nYou anoint my head with oil.\nMy cup runs over.\nSurely goodness and loving kindness shall follow me all the days of my life,\nand I will dwell in the Lord’s house forever.",
        Personalise: "You prepare a table before me\nin the presence of my enemies.\nYou anoint my head with oil.\nMy cup runs over.\nSurely goodness and loving kindness shall follow me all the days of my life,\nand I will dwell in the house of the Lord forever.",
        Display: true,
        Audio: "101_annoint.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00102", 
        Collection: "Salvation",
        Book: "1 Thessalonians", 
        Chapter: "4",
        V: [16,17],
        Version: "WEB",
        Verse: "For the Lord himself will descend from heaven with a shout, with the voice of the archangel and with God’s trumpet. The dead in Christ will rise first, then we who are alive, who are left, will be caught up together with them in the clouds, to meet the Lord in the air. So we will be with the Lord forever.",
        Personalise: "For the Lord himself will descend from heaven with a shout, with the voice of the archangel and with God’s trumpet. The dead in Christ will rise first, then we who are alive, who are left, will be caught up together with them in the clouds, to meet the Lord in the air. So we will be with the Lord forever.",
        Display: true,
        Audio: "102_rise_first.mp3",
        Deleteable: false,
        Favourite: false,
    },
        
    
    {   Key: "00103", 
        Collection: "Salvation",
        Book: "2 Corinthians", 
        Chapter: "5",
        V: [1],
        Version: "WEB",
        Verse: "For we know that if the earthly house of our tent is dissolved, we have a building from God, a house not made with hands, eternal, in the heavens.",
        Personalise: "I know that if my earthly body is dissolved, I have a building from God, a house not made with hands, eternal, in the heavens.",
        Display: true,
        Audio: "103_earthly_body.mp3",
        Deleteable: false,
        Favourite: false,
    },
   
    
    {   Key: "00104", 
        Collection: "Loved",
        Book: "Romans", 
        Chapter: "5",
        V: [8],
        Version: "WEB",
        Verse: "But God commends his own love toward us, in that while we were yet sinners, Christ died for us.",
        Personalise: "God showed His own love toward me, in that while I was yet a sinner, Christ died for me.",
        Display: true,
        Audio: "104_while_a_sinner.mp3",
        Deleteable: false,
        Favourite: false,
    },
   
    
    {   Key: "00105", 
        Collection: "Loved",
        Book: "Jeremiah", 
        Chapter: "31",
        V: [3],
        Version: "WEB",
        Verse: "The Lord appeared of old to me, saying, “Yes, I have loved you with an everlasting love. Therefore, I have drawn you with loving kindness.",
        Personalise: "God loves me with an everlasting love. He has drawn me with loving kindness.",
        Display: true,
        Audio: "105_everlasting.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00106", 
        Collection: "Salvation",
        Book: "Galatians", 
        Chapter: "5",
        V: [1],
        Version: "WEB",
        Verse: "Stand firm therefore in the liberty by which Christ has made us free, and don’t be entangled again with a yoke of bondage.",
        Personalise: "I stand firm in the freedom Christ has given me, I will not be entangled again with a yoke of bondage.",
        Display: true,
        Audio: "106_freedom.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00107", 
        Collection: "Comfort",
        Book: "Psalms", 
        Chapter: "147",
        V: [3],
        Version: "WEB",
        Verse: "He heals the broken in heart,\nand binds up their wounds.",
        Personalise: "He heals my broken heart,\nand binds up my wounds.",
        Display: true,
        Audio: "107_broken_heart.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00108", 
        Collection: "Identity",
        Book: "Philippians", 
        Chapter: "3",
        V: [20],
        Version: "WEB",
        Verse: "For our citizenship is in heaven, from where we also wait for a Savior, the Lord Jesus Christ...",
        Personalise: "My citizenship is in heaven, from where I am waiting my Saviour, the Lord Jesus Christ...",
        Display: true,
        Audio: "108_citizenship.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00109", 
        Collection: "Salvation",
        Book: "Ephesians", 
        Chapter: "2",
        V: [8,10],
        Version: "WEB",
        Verse: "...for by grace you have been saved through faith, and that not of yourselves; it is the gift of God... For we are his workmanship, created in Christ Jesus for good works, which God prepared before that we would walk in them.",
        Personalise: "I have been saved by grace through faith, and that is not of myself; it is the gift of God. I am His workmanship, created in Christ Jesus for good works, which God has prepared that I should walk in them.",
        Display: true,
        Audio: "109_workmanship.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00110", 
        Collection: "Peace",
        Book: "John", 
        Chapter: "16",
        V: [33],
        Version: "WEB",
        Verse: "I have told you these things, that in me you may have peace. In the world you have trouble; but cheer up! I have overcome the world.",
        Personalise: "In Jesus I have peace. In this world I will have trouble, but He has overcome the world.",
        Display: true,
        Audio: "110_trouble.mp3",
        Deleteable: false,
        Favourite: false,
    },

       
    
    {   Key: "00111", 
        Collection: "Peace",
        Book: "Philippians", 
        Chapter: "4",
        V: [6,7],
        Version: "WEB",
        Verse: "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.",
        Personalise: "I will not be anxious about anything, but in everything, by prayer and petition with thanksgiving, I make my requests known to God. And the peace of God, which surpasses all understanding, guards my heart and my thoughts in Christ Jesus.",
        Display: true,
        Audio: "111_guard.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00112", 
        Collection: "Peace",
        Book: "2 Thessalonians", 
        Chapter: "3",
        V: [16],
        Version: "WEB",
        Verse: "Now may the Lord of peace himself give you peace at all times in all ways. The Lord be with you all.",
        Personalise: "The Lord of peace gives me peace at all times and in all ways. The Lord is with me.",
        Display: true,
        Audio: "112_lord_of_peace.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00113", 
        Collection: "Peace",
        Book: "Psalms", 
        Chapter: "4",
        V: [8],
        Version: "WEB",
        Verse: "In peace I will both lay myself down and sleep,\nfor you, Lord alone, make me live in safety.",
        Personalise: "In peace I lie down and sleep,\nfor you, Lord alone, make me live in safety.",
        Display: true,
        Audio: "113_safety.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00114", 
        Collection: "Peace",
        Book: "Isaiah", 
        Chapter: "26",
        V: [3],
        Version: "WEB",
        Verse: "You will keep whoever’s mind is steadfast in perfect peace, because he trusts in you.",
        Personalise: "You keep my mind in perfect peace as I fix my thoughts on You Lord. I trust in You.",
        Display: true,
        Audio: "114_thoughts.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00115", 
        Collection: "Peace",
        Book: "Colossians", 
        Chapter: "3",
        V: [15],
        Version: "WEB",
        Verse: "And let the peace of God rule in your hearts, to which also you were called in one body, and be thankful.",
        Personalise: "The peace of Christ rules in my heart.",
        Display: true,
        Audio: "115_rules.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00116", 
        Collection: "Peace",
        Book: "Jude", 
        Chapter: "1",
        V: [2],
        Version: "WEB",
        Verse: "May mercy, peace, and love be multiplied to you.",
        Personalise: "Mercy, peace, and love are being multiplied to me.",
        Display: true,
        Audio: "116_multiplied.mp3",
        Deleteable: false,
        Favourite: false,
    },
       
    
    {   Key: "00117", 
        Collection: "Peace",
        Book: "Psalms", 
        Chapter: "29",
        V: [11],
        Version: "WEB",
        Verse: "The Lord will give strength to his people.\nThe Lord will bless his people with peace.",
        Personalise: "The Lord gives me strength. The Lord has blessed me with peace.",
        Display: true,
        Audio: "117_blessed_with_peace.mp3",
        Deleteable: false,
        Favourite: false,
    },

        
    {   Key: "00118", 
        Collection: "Peace",
        Book: "Romans", 
        Chapter: "5",
        V: [1],
        Version: "WEB",
        Verse: "Being therefore justified by faith, we have peace with God through our Lord Jesus Christ.",
        Personalise: "I am justified by faith and have peace with God through my Lord Jesus Christ.",
        Display: true,
        Audio: "118_justified.mp3",
        Deleteable: false,
        Favourite: false,
    },


        
    {   Key: "00119", 
        Collection: "Loved",
        Book: "Isaiah", 
        Chapter: "51",
        V: [10],
        Version: "WEB",
        Verse: `"For the mountains may depart,\nand the hills be removed;\nbut my loving kindness will not depart from you,\nand my covenant of peace will not be removed,"\nsays the Lord who has mercy on you.`,
        Personalise: "For the mountains may depart,\nand the hills be removed;\nbut God's loving kindness will not leave me,\nand His covenant of peace will not be removed.",
        Display: true,
        Audio: "119_mountains.mp3",
        Deleteable: false,
        Favourite: false,
    },


        
    {   Key: "00120", 
        Collection: "Peace",
        Book: "Romans", 
        Chapter: "16",
        V: [20],
        Version: "WEB",
        Verse: "And the God of peace will quickly crush Satan under your feet. The grace of our Lord Jesus Christ be with you.",
        Personalise: "The God of peace will quickly crush Satan under my feet. The grace of my Lord Jesus Christ is with me.",
        Display: true,
        Audio: "120_feet.mp3",
        Deleteable: false,
        Favourite: false,
    },


        
    {   Key: "00121", 
        Collection: "Protection",
        Book: "Isaiah", 
        Chapter: "43",
        V: [2],
        Version: "WEB",
        Verse: "When you pass through the waters, I will be with you, and through the rivers, they will not overflow you. When you walk through the fire, you will not be burned, and flame will not scorch you.",
        Personalise: "When I pass through the waters, You will be with me. When I pass through the rivers, they will not sweep me away. When I walk through the fire, I will not be burned, and the flame will not scorch me.",
        Display: true,
        Audio: "121_rivers.mp3",
        Deleteable: false,
        Favourite: false,
    },


        
    {   Key: "00122", 
        Collection: "Protection",
        Book: "Isaiah",
        Chapter: "54",
        V: [17],
        Version: "WEB",
        Verse: `"No weapon that is formed against you will prevail; and you will condemn every tongue that rises against you in judgment. This is the heritage of the Lord’s servants, and their righteousness is of me,” says the Lord."`,
        Personalise: "No weapon that is formed against me will prevail and every tongue that rises against me in judgment, I condemn. My righteousness is of the Lord.",
        Display: true,
        Audio: "122_weapon.mp3",
        Deleteable: false,
        Favourite: false,
    },


        
    {   Key: "00123", 
        Collection: "Identity",
        Book: "Genesis", 
        Chapter: "1",
        V: [27],
        Version: "WEB",
        Verse: "God created man in his own image. In God’s image he created him; male and female he created them.",
        Personalise: "I am created in God's own image.",
        Display: true,
        Audio: "123_image.mp3",
        Deleteable: false,
        Favourite: false,
    },


        
    {   Key: "00124", 
        Collection: "Loved",
        Book: "Psalms", 
        Chapter: "17",
        V: [8],
        Version: "WEB",
        Verse: "Keep me as the apple of your eye.\nHide me under the shadow of your wings.",
        Personalise: "You keep me as the apple of Your eye. You hide me beneath the shadow of your wings.",
        Display: true,
        Audio: "124_apple.mp3",
        Deleteable: false,
        Favourite: false,
    },


        
    {   Key: "00125", 
        Collection: "Identity",
        Book: "John", 
        Chapter: "15",
        V: [16],
        Version: "WEB",
        Verse: "You didn’t choose me, but I chose you and appointed you, that you should go and bear fruit, and that your fruit should remain; that whatever you will ask of the Father in my name, he may give it to you.",
        Personalise: "I am chosen by Jesus and appointed by Him to bear good fruit.",
        Display: true,
        Audio: "125_chosen.mp3",
        Deleteable: false,
        Favourite: false,
    },


        
    {   Key: "00126", 
        Collection: "Identity",
        Book: "Ephesians", 
        Chapter: "1",
        V: [4,5],
        Version: "WEB",
        Verse: "...even as he chose us in him before the foundation of the world, that we would be holy and without defect before him in love, having predestined us for adoption as children through Jesus Christ to himself, according to the good pleasure of his desire.",
        Personalise: "I was chosen in Christ before the foundation of the world, that I would be holy and without defect before Him in love. I was predestined to be adopted as His child through Jesus Christ, according to His good pleasure.",
        Display: true,
        Audio: "126_predestined.mp3",
        Deleteable: false,
        Favourite: false,
    },


        
    {   Key: "00127", 
        Collection: "Comfort",
        Book: "Matthew", 
        Chapter: "28",
        V: [20],
        Version: "WEB",
        Verse: `"...Behold, I am with you always, even to the end of the age."`,
        Personalise: "Jesus is with me always, even unto the end of the age.",
        Display: true,
        Audio: "127_age.mp3",
        Deleteable: false,
        Favourite: false,
    },


       
/*     {   Key: "00128", 
        Collection: "Jesus",
        Book: "Genesis", 
        Chapter: "3",
        V: [15],
        Version: "WEB",
        Verse: "I will put hostility between you and the woman, and between your offspring and her offspring. He will bruise your head, and you will bruise his heel.",
        Personalise: "Jesus is the woman’s offspring who crushes the serpent’s head.",
        Display: true,
        Audio: "128_crush.mp3",
        Deleteable: false,
        Favourite: false,
    }, */

    {   Key: "00129", 
        Collection: "Jesus",
        Book: "Song of Solomon", 
        Chapter: "5",
        V: [10],
        Version: "WEB",
        Verse: "My beloved is white and ruddy.\nThe best among ten thousand.",
        Personalise: "Jesus is the Chief among ten thousand.",
        Display: true,
        Audio: "129_chief.mp3",
        Deleteable: false,
        Favourite: false,
    },


       
    {   Key: "00130", 
        Collection: "Jesus",
        Book: "Song of Solomon", 
        Chapter: "5",
        V: [16],
        Version: "WEB",
        Verse: "His mouth is sweetness;\nyes, he is altogether lovely.\nThis is my beloved, and this is my friend,\ndaughters of Jerusalem.",
        Personalise: "Jesus is altogether lovely, my beloved and my friend.",
        Display: true,
        Audio: "130_altogether.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00131", 
        Collection: "Jesus",
        Book: "Isaiah", 
        Chapter: "9",
        V: [6],
        Version: "WEB",
        Verse: "For a child is born to us. A son is given to us; and the government will be on his shoulders. His name will be called Wonderful Counsellor, Mighty God, Everlasting Father, Prince of Peace.",
        Personalise: "Jesus is the Son given unto us. The government is on His shoulders. His name is called Wonderful Counsellor, Mighty God, Everlasting Father, Prince of Peace.",
        Display: true,
        Audio: "131_son_given.mp3",
        Deleteable: false,
        Favourite: false,
    },
 


       
    {   Key: "00132", 
        Collection: "Jesus",
        Book: "Isaiah", 
        Chapter: "53",
        V: [5],
        Version: "WEB",
        Verse: "But he was pierced for our transgressions.\nHe was crushed for our iniquities.\nThe punishment that brought our peace was on him;\nand by his wounds we are healed.",
        Personalise: "Jesus is the one who was pierced for our transgressions and crushed for our iniquities.",
        Display: true,
        Audio: "132_pierced.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00133", 
        Collection: "Jesus",
        Book: "Malachi", 
        Chapter: "4",
        V: [2],
        Version: "WEB",
        Verse: "But to you who fear my name shall the sun of righteousness arise with healing in its wings. You will go out, and leap like calves of the stall.",
        Personalise: "Jesus is the Sun of Righteousness, who has risen with healing in His wings.",
        Display: true,
        Audio: "133_wings.mp3",
        Deleteable: false,
        Favourite: false,
    },
 


       
    {   Key: "00134", 
        Collection: "Jesus",
        Book: "Matthew", 
        Chapter: "12",
        V: [18],
        Version: "WEB",
        Verse: "Behold, my servant whom I have chosen,\nmy beloved in whom my soul is well pleased.\nI will put my Spirit on him.\nHe will proclaim justice to the nations.",
        Personalise: "Jesus is the chosen Servant, the Father’s Beloved, on whom the Spirit rests. ",
        Display: true,
        Audio: "134_chosen.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00135", 
        Collection: "Jesus",
        Book: "Matthew", 
        Chapter: "16",
        V: [16],
        Version: "WEB",
        Verse: `Simon Peter answered, “You are the Christ, the Son of the living God.”`,
        Personalise: "Jesus is the Christ, the Son of the living God.",
        Display: true,
        Audio: "135_christ.mp3",
        Deleteable: false,
        Favourite: false,
    },
 
   
    {   Key: "00136", 
        Collection: "Jesus",
        Book: "Luke", 
        Chapter: "1",
        V: [32],
        Version: "WEB",
        Verse: "He will be great and will be called the Son of the Most High. The Lord God will give him the throne of his father David.",
        Personalise: "Jesus is the Son of the Most High. He has been given the throne of David.",
        Display: true,
        Audio: "136_throne.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00137", 
        Collection: "Jesus",
        Book: "John", 
        Chapter: "1",
        V: [1],
        Version: "WEB",
        Verse: "In the beginning was the Word, and the Word was with God, and the Word was God.",
        Personalise: "Jesus was the Word in the beginning with God, who was Himself God.",
        Display: true,
        Audio: "137_word.mp3",
        Deleteable: false,
        Favourite: false,
    },
 

       
    {   Key: "00138", 
        Collection: "Jesus",
        Book: "John", 
        Chapter: "1",
        V: [14],
        Version: "WEB",
        Verse: "The Word became flesh, and lived among us. We saw his glory, such glory as of the one and only Son of the Father, full of grace and truth.",
        Personalise: "Jesus is the Word made flesh. The one and only Son of the Father, full of grace and truth.",
        Display: true,
        Audio: "138_grace_and_truth.mp3",
        Deleteable: false,
        Favourite: false,
    },


    {   Key: "00139", 
        Collection: "Jesus",
        Book: "John", 
        Chapter: "1",
        V: [29],
        Version: "WEB",
        Verse: `The next day, he saw Jesus coming to him, and said, “Behold, the Lamb of God, who takes away the sin of the world!"`,
        Personalise: "Jesus is the Lamb of God who takes away the sin of the world.",
        Display: true,
        Audio: "139_lamb_of_god.mp3",
        Deleteable: false,
        Favourite: false,
    },
 
       
    {   Key: "00140", 
        Collection: "Jesus",
        Book: "John", 
        Chapter: "6",
        V: [33],
        Version: "WEB",
        Verse: "For the bread of God is that which comes down out of heaven, and gives life to the world.",
        Personalise: "Jesus is the Bread of God which comes down out of heaven, and gives life to the world.",
        Display: true,
        Audio: "140_bread.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00141", 
        Collection: "Jesus",
        Book: "John", 
        Chapter: "8",
        V: [12],
        Version: "WEB",
        Verse: `Again, therefore, Jesus spoke to them, saying, “I am the light of the world. He who follows me will not walk in the darkness, but will have the light of life.”`,
        Personalise: "Jesus is the Light of the world.",
        Display: true,
        Audio: "141_light.mp3",
        Deleteable: false,
        Favourite: false,
    },
 
       
    {   Key: "00142", 
        Collection: "Jesus",
        Book: "John", 
        Chapter: "10",
        V: [11],
        Version: "WEB",
        Verse: "I am the good shepherd. The good shepherd lays down his life for the sheep.",
        Personalise: "Jesus is the Good Shepherd who lays down his life for the sheep.",
        Display: true,
        Audio: "142_shepherd.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00143", 
        Collection: "Jesus",
        Book: "John", 
        Chapter: "11",
        V: [25],
        Version: "WEB",
        Verse: `Jesus said to her, “I am the resurrection and the life. He who believes in me will still live, even if he dies."`,
        Personalise: "Jesus is the Resurrection and the Life.",
        Display: true,
        Audio: "143_resurrection.mp3",
        Deleteable: false,
        Favourite: false,
    },
 
       
    {   Key: "00144", 
        Collection: "Jesus",
        Book: "John", 
        Chapter: "14",
        V: [6],
        Version: "WEB",
        Verse: `Jesus said to him, “I am the way, the truth, and the life. No one comes to the Father, except through me."`,
        Personalise: "Jesus is the Way, the Truth, the Life.",
        Display: true,
        Audio: "144_way.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00145", 
        Collection: "Jesus",
        Book: "Acts", 
        Chapter: "3",
        V: [14,15],
        Version: "WEB",
        Verse: "But you denied the Holy and Righteous One and asked for a murderer to be granted to you, and killed the Prince of life, whom God raised from the dead, to which we are witnesses.",
        Personalise: "Jesus is the Holy and Righteous One. The Prince of Life.",
        Display: true,
        Audio: "145_prince.mp3",
        Deleteable: false,
        Favourite: false,
    },
 
       
    {   Key: "00146", 
        Collection: "Jesus",
        Book: "Romans", 
        Chapter: "1",
        V: [3,4],
        Version: "WEB",
        Verse: "concerning his Son, who was born of the offspring of David according to the flesh, who was declared to be the Son of God with power, according to the Spirit of holiness, by the resurrection from the dead, Jesus Christ our Lord.",
        Personalise: "Jesus, the Offspring of David, was declared to be the Son of God with power, by the resurrection from the dead.",
        Display: true,
        Audio: "146_power.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00147", 
        Collection: "Jesus",
        Book: "1 Corinthians", 
        Chapter: "1",
        V: [30],
        Version: "WEB",
        Verse: "Because of him, you are in Christ Jesus, who was made to us wisdom from God, and righteousness and sanctification, and redemption:",
        Personalise: "Jesus is our wisdom, righteousness, sanctification and redemption.",
        Display: true,
        Audio: "147_wisdom.mp3",
        Deleteable: false,
        Favourite: false,
    },
 

       
    {   Key: "00148", 
        Collection: "Jesus",
        Book: "Isaiah", 
        Chapter: "28",
        V: [16],
        Version: "WEB",
        Verse: "Therefore the Lord God says, “Behold, I lay in Zion for a foundation a stone, a tried stone, a precious cornerstone of a sure foundation. He who believes shall not act hastily.",
        Personalise: "Jesus is the Precious Cornerstone of a sure foundation.",
        Display: true,
        Audio: "148_foundation.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00149", 
        Collection: "Jesus",
        Book: "Philippians", 
        Chapter: "2",
        V: [7,8],
        Version: "WEB",
        Verse: "but emptied himself, taking the form of a servant, being made in the likeness of men. And being found in human form, he humbled himself, becoming obedient to the point of death, yes, the death of the cross.",
        Personalise: "Jesus is the Servant who humbled himself, becoming obedient unto death.",
        Display: true,
        Audio: "149_servant.mp3",
        Deleteable: false,
        Favourite: false,
    },
 
       
    {   Key: "00150", 
        Collection: "Jesus",
        Book: "Philippians", 
        Chapter: "2",
        V: [9],
        Version: "WEB",
        Verse: "Therefore God also highly exalted him, and gave to him the name which is above every name.",
        Personalise: "Jesus has been highly exalted and given the name above every name.",
        Display: true,
        Audio: "150_name.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00151", 
        Collection: "Jesus",
        Book: "Colossians", 
        Chapter: "1",
        V: [15],
        Version: "WEB",
        Verse: "He is the image of the invisible God, the firstborn of all creation.",
        Personalise: "Jesus is the image of the invisible God, the firstborn of all creation.",
        Display: true,
        Audio: "151_image.mp3",
        Deleteable: false,
        Favourite: false,
    },
 

    {   Key: "00152", 
        Collection: "Jesus",
        Book: "Colossians", 
        Chapter: "1",
        V: [17,18],
        Version: "WEB",
        Verse: "He is before all things, and in him all things are held together. He is the head of the body, the assembly, who is the beginning, the firstborn from the dead, that in all things he might have the preeminence.",
        Personalise: "Jesus is before all things, and in Him all things are held together. He is the Head of the Body. He is the Beginning, the First-born from the dead.",
        Display: true,
        Audio: "152_before.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00153", 
        Collection: "Jesus",
        Book: "Hebrews", 
        Chapter: "1",
        V: [3],
        Version: "WEB",
        Verse: "His Son is the radiance of his glory, the very image of his substance, and upholding all things by the word of his power, who, when he had by himself purified us of our sins, sat down on the right hand of the Majesty on high.",
        Personalise: "Jesus is the radiance of God’s glory, the very image of His being, who upholds all things by the word of His power.",
        Display: true,
        Audio: "153_upholds.mp3",
        Deleteable: false,
        Favourite: false,
    },
 

    {   Key: "00154", 
        Collection: "Jesus",
        Book: "Hebrews", 
        Chapter: "13",
        V: [8],
        Version: "WEB",
        Verse: "Jesus Christ is the same yesterday, today, and forever.",
        Personalise: "Jesus Christ is the same yesterday, today, and forever.",
        Display: true,
        Audio: "154_yesterday.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00155", 
        Collection: "Jesus",
        Book: "Hebrews", 
        Chapter: "4",
        V: [14],
        Version: "WEB",
        Verse: "Having then a great high priest who has passed through the heavens, Jesus, the Son of God, let’s hold tightly to our confession.",
        Personalise: "Jesus is the Great High Priest who has passed through the heavens.",
        Display: true,
        Audio: "155_priest.mp3",
        Deleteable: false,
        Favourite: false,
    },
 
       
    {   Key: "00156", 
        Collection: "Jesus",
        Book: "Hebrews", 
        Chapter: "12",
        V: [2],
        Version: "WEB",
        Verse: "looking to Jesus, the author and perfecter of faith, who for the joy that was set before him endured the cross, despising its shame, and has sat down at the right hand of the throne of God.",
        Personalise: "Jesus is the Author and Perfecter of our faith. He endured the cross and is now seated at the right hand of the throne of God.",
        Display: true,
        Audio: "156_author.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00157", 
        Collection: "Jesus",
        Book: "Hebrews", 
        Chapter: "5",
        V: [9],
        Version: "WEB",
        Verse: "Having been made perfect, he became to all of those who obey him the author of eternal salvation,",
        Personalise: "Jesus is the Author of eternal salvation to all who obey Him.",
        Display: true,
        Audio: "157_eternal.mp3",
        Deleteable: false,
        Favourite: false,
    },
 


       
    {   Key: "00158", 
        Collection: "Jesus",
        Book: "Revelation", 
        Chapter: "1",
        V: [5],
        Version: "WEB",
        Verse: "and from Jesus Christ, the faithful witness, the firstborn of the dead, and the ruler of the kings of the earth. To him who loves us, and washed us from our sins by his blood—",
        Personalise: "Jesus Christ is the Faithful Witness, the Firstborn of the dead and the Ruler of the kings of the earth.",
        Display: true,
        Audio: "158_faithful.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00159", 
        Collection: "Jesus",
        Book: "Revelation", 
        Chapter: "1",
        V: [7],
        Version: "WEB",
        Verse: "Behold, he is coming with the clouds, and every eye will see him, including those who pierced him. All the tribes of the earth will mourn over him. Even so, Amen.",
        Personalise: "Jesus is coming with the clouds, and every eye will see him.",
        Display: true,
        Audio: "159_clouds.mp3",
        Deleteable: false,
        Favourite: false,
    },
 

    {   Key: "00160", 
        Collection: "Jesus",
        Book: "Revelation", 
        Chapter: "1",
        V: [14,15,16],
        Version: "WEB",
        Verse: "His head and his hair were white as white wool, like snow. His eyes were like a flame of fire. His feet were like burnished brass, as if it had been refined in a furnace. His voice was like the voice of many waters. He had seven stars in his right hand. Out of his mouth proceeded a sharp two-edged sword. His face was like the sun shining at its brightest.",
        Personalise: "Jesus’ eyes are like a flame of fire. His voice is like the sound of many waters. His face is like the sun shining in all its strength.",
        Display: true,
        Audio: "160_eyes.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00161", 
        Collection: "Jesus",
        Book: "Revelation", 
        Chapter: "1",
        V: [18],
        Version: "WEB",
        Verse: "He laid his right hand on me, saying, “Don’t be afraid. I am the first and the last, and the Living one. I was dead, and behold, I am alive forever and ever. Amen. I have the keys of Death and of Hades.",
        Personalise: "Jesus is the First and the Last, the Living One. He was dead, and is now alive forever and ever.",
        Display: true,
        Audio: "161_living.mp3",
        Deleteable: false,
        Favourite: false,
    },
 



    {   Key: "00163", 
        Collection: "Jesus",
        Book: "Revelation", 
        Chapter: "5",
        V: [12],
        Version: "WEB",
        Verse: "saying with a loud voice, “Worthy is the Lamb who has been killed to receive the power, wealth, wisdom, strength, honour, glory, and blessing!”",
        Personalise: "Jesus is the Lamb who was slain. He is worthy to receive power, wealth, wisdom, strength, honour, glory and blessing.",
        Display: true,
        Audio: "163_lamb.mp3",
        Deleteable: false,
        Favourite: false,
    },


    {   Key: "00164", 
        Collection: "Jesus",
        Book: "Revelation", 
        Chapter: "5",
        V: [5],
        Version: "WEB",
        Verse: "One of the elders said to me, “Don’t weep. Behold, the Lion who is of the tribe of Judah, the Root of David, has overcome: he who opens the book and its seven seals.”",
        Personalise: "Jesus is the Lion of the tribe of Judah, the Root of David, who has overcome.",
        Display: true,
        Audio: "164_lion.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00165", 
        Collection: "Jesus",
        Book: "Revelation", 
        Chapter: "7",
        V: [17],
        Version: "WEB",
        Verse: "for the Lamb who is in the middle of the throne shepherds them and leads them to springs of life-giving waters. And God will wipe away every tear from their eyes.",
        Personalise: "Jesus is the Lamb in the middle of the throne who shepherds His people leading them to life-giving waters.",
        Display: true,
        Audio: "165_waters.mp3",
        Deleteable: false,
        Favourite: false,
    },


    {   Key: "00166", 
        Collection: "Jesus",
        Book: "Revelation", 
        Chapter: "19",
        V: [16],
        Version: "WEB",
        Verse: `He has on his garment and on his thigh a name written, “KING OF KINGS, AND LORD OF LORDS.”`,
        Personalise: "Jesus is the King of Kings and Lord of Lords.",
        Display: true,
        Audio: "166_king.mp3",
        Deleteable: false,
        Favourite: false,
    },

    {   Key: "00167", 
        Collection: "Jesus",
        Book: "Revelation", 
        Chapter: "22",
        V: [20],
        Version: "WEB",
        Verse: `He who testifies these things says, “Yes, I come quickly.”\nAmen! Yes, come, Lord Jesus.`,
        Personalise: `Jesus is the one who says, "I come quickly!"\nAmen! Even so, come, Lord Jesus.`,
        Display: true,
        Audio: "167_come_quickly.mp3",
        Deleteable: false,
        Favourite: false,
    },

];

export default VerseData;
